version: '3'

services:
  api:
    restart: unless-stopped
    build: ./api
    links: 
      - redis
    env_file:
      - .env
    volumes:
      - ./api:/usr/src/app
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
    networks:
      - sunset

  app:
    restart: unless-stopped
    build: ./app
    env_file:
      - .env
    volumes:
      - ./app:/usr/src/app
    depends_on:
      - api
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
    networks:
      - sunset

  nginx:
    restart: unless-stopped
    build: ./nginx
    container_name: nginx
    ports:
      - 443:443
    links:
      - api
      - app
      - imcargo
    depends_on:
      - api
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
    networks:
      - sunset

  varnish:
    restart: unless-stopped
    build: ./varnish
    container_name: varnish_cache
    links:
      - nginx
    depends_on:
      - nginx
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
    networks:
      - sunset

  imcargo:
    build: ./imcargo
    container_name: imcargo
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8080:8080"
    volumes:
      - ./static:/go/src/imcargo/static
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
    networks:
      - sunset
  
  redis:
    restart: unless-stopped
    build: ./redis
    container_name: cache
    ports:
      - "6379:6379"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
    networks:
      - sunset

networks:
  sunset:
    driver: bridge
