version: '3'

services:
  node-app:
    restart: unless-stopped
    build: ./node-app
    env_file:
      - .env
    volumes:
      - ./node-app:/usr/src/app
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
    networks:
      - sunset

  nginx:
    restart: unless-stopped
    build: ./nginx
    container_name: nginx
    ports:
      - 443:443
    links:
      - node-app
    depends_on:
      - node-app
    volumes:
      - certs:/etc/letsencrypt
      - certs-data:/data/letsencrypt
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
    networks:
      - sunset

  varnish:
    restart: unless-stopped
    build: ./varnish
    container_name: varnish_cache
    links:
      - nginx
    depends_on:
      - nginx
    ports:
      - "80:80"
    logging:
      driver: "json-file"
      options:
        max-size: "100MB"
        max-file: "3"
    networks:
      - sunset

volumes:
  certs:
  certs-data:

networks:
  sunset:
    driver: bridge