name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2

    - name: Cacheting node_nodules
      id: cache-node_modules
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/node-app/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

    - name: Cacheting .next/cache
      id: cache-next
      uses: actions/cache@v2
      with:
        path: ${{ github.workspace }}/.next/cache
        key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

    - name: Installing node_modules
      run: |
        cd node-app
        yarn

    - name: Building The Source
      run: |
        cd node-app
        yarn build
  
    - name: Generating .env
      run: kvilo exp-env > .env

    - name: Building Node Container 
      run: sudo docker-compose build node-app
    
    - name: Restarting Node Container 
      run: sudo docker-compose restart node-app
      

